### ISSUE TITLE
Nach Installation werden Wertpapiere ohne Beträge angezeigt

### ISSUE THREAD

**Issue by jonathanlang** [Struppie/MoneyMoney---Extensions#1]
Extension installiert, Login erfolgreich, drei Wertpapiere werden für den Fairr Vertrag angezeigt, allerdings alle mit Betrag 0€.
Muss das Scraping aktualisiert werden?

**Comment by Struppie** [comment]
Hallo - ja, korrekt. Die Bank hat wohl vor ca. 2-3 Tagen eine kleine Modifikation vorgenommen. Ich habe eine neue Version der Extension erstellt mit der es wieder funktioniert und sobald ich vom MoneyMoney Hersteller eine signierter Version zurückerhalten habe, werde ich das Update bereitstellen.
Danke für den Hinweis!

**Comment by Struppie** [comment]
Fix steht nun bereit mit commit #a113dcc

**Comment by jonathanlang** [comment]
Danke!
